# H2 Database
spring.datasource.url=jdbc:h2:file:C:/Users/Slava/test;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Spring Security
# spring.security.user.name=admin
# spring.security.user.password=password

# Swagger (????????)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.cache.disabled=true

# Liquibase (???????? ???? ?????)
spring.liquibase.enabled=false

# Logging
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Server
server.error.whitelabel.enabled=false
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=0
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Mail (?????? ???? ?????????)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=???_email@gmail.com
spring.mail.password=???_??????_???_????_??????????
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true